description: All FEATURE_TYPE_L3_BASE configuration.
properties:
  ipv4Subnet:
    description: |-
      Required. IPv4 subnet used to establish L3 connectivity for the customer

      Note: The IP address must have the subnet mask applied to it.
    type: string
  ipv4SubnetPrefixLength:
    description: Required. IPv4 subnet prefix length.
    format: int32
    type: integer
  ipv6Subnet:
    description: |-
      Optional. IPv6 subnet used to establish L3 connectivity for the customer

      Note: The IP address must have the subnet mask applied to it.
    type: string
  ipv6SubnetPrefixLength:
    description: Optional. IPv6 subnet prefix length.
    format: int32
    type: integer
  mtuBytes:
    description: |-
      Required. MTU for VLAN attachments.

      Special note: This represents the MTU at the connection points
      between providers, there may be further MTU limitations within provider
      networks.
    format: int32
    type: integer
  vlanId:
    description: |-
      Required. VLAN ID used by the connection.

      VLAN 1024 and lower are reserved and cannot have features associated with
      them.  Otherwise, a provider may select from any available VLANs.
    format: int32
    type: integer
  providerBgpConfigs:
    description: |-
      Required. A mapping of provider ID to all BGP session attributes the provider
      should use.
    items:
      $ref: "provider_bgp_config.yaml"
    type: array
  md5BgpPassword:
    description: Shared MD5 password for BGP sessions.
    type: string
type: object
