description: |-
  All parameters needed for a provider to configure a BGP session
  associated with a channel.
properties:
  provider:
    description: |-
      Required. The resource name of the provider that this BGP configuration is
      associated with.
    type: string
  asn:
    description: Required. The ASN associated with the provider.
    format: int32
    type: integer
  hostIpv4:
    description: Required. IPv4 address hosting BGP session for provider.
    type: string
  hostIpv6:
    description: Optional. IPv6 address hosting BGP session for provider.
    type: string
type: object
