get:
  description: List all environments associated with a CSP.
  operationId: ListEnvironments
  parameters:
  - $ref: "../../parameters/_index.yaml#/parameters/provider"
  - description: |-
      The maximum number of environments to return. The service may return fewer
      than this value.
    explode: true
    in: query
    name: pageSize
    required: false
    schema:
      format: int32
      type: integer
    style: form
  - description: |-
      A page token, received from a previous `ListEnvironments` call.
      Provide this to retrieve the subsequent page.

      When paginating, all other parameters provided to `ListEnvironments` must
      match the call that provided the page token.
    explode: true
    in: query
    name: pageToken
    required: false
    schema:
      type: string
    style: form
  responses:
    default:
      content:
        application/json:
          schema:
            $ref: "../../schemas/environment/list_environments_response.yaml"
      description: Successful operation
  security: []
  tags:
  - Environments
