get:
  description: Get details about a specific environment.
  operationId: GetEnvironment
  parameters:
  - $ref: "../../parameters/_index.yaml#/parameters/provider"
  - $ref: "../../parameters/_index.yaml#/parameters/environment"
  responses:
    default:
      content:
        application/json:
          schema:
            $ref: "../../schemas/environment/environment.yaml"
      description: Successful operation
  security: []
  tags:
  - Environments
