AllEnvironments:
  get:
    description: List all environments associated with a CSP.
    operationId: ListEnvironments
    parameters:
    - $ref: "../parameters/_index.yaml#/parameters/provider"
    - description: |-
        The maximum number of environments to return. The service may return fewer
        than this value.
      explode: true
      in: query
      name: pageSize
      required: false
      schema:
        format: int32
        type: integer
      style: form
    - description: |-
        A page token, received from a previous `ListEnvironments` call.
        Provide this to retrieve the subsequent page.

        When paginating, all other parameters provided to `ListEnvironments` must
        match the call that provided the page token.
      explode: true
      in: query
      name: pageToken
      required: false
      schema:
        type: string
      style: form
    responses:
      default:
        content:
          application/json:
            schema:
              $ref: "../schemas/environment.yaml#/ListEnvironmentsResponse"
        description: Successful operation
    security: []
    tags:
    - Environments
OneEnvironment:
  get:
    description: Get details about a specific environment.
    operationId: GetEnvironment
    parameters:
    - $ref: "../parameters/_index.yaml#/parameters/provider"
    - $ref: "../parameters/_index.yaml#/parameters/environment"
    responses:
      default:
        content:
          application/json:
            schema:
              $ref: "../schemas/environment.yaml#/Environment"
        description: Successful operation
    security: []
    tags:
    - Environments
ConfirmActivationKey:
  post:
    description: |-
      Allows a provider to validate the authenticity of an activation key before
      creating a connection associated with it.

      FUTURE: In the future, we may allow providers to convey additional
              provisioning information excluded from the activation key in their
              response.
    operationId: ConfirmActivationKey
    parameters:
    - $ref: "../parameters/_index.yaml#/parameters/provider"
    - $ref: "../parameters/_index.yaml#/parameters/environment"
    requestBody:
      content:
        application/json:
          schema:
            $ref: "../schemas/environment.yaml#/ConfirmActivationKeyRequest"
      description: The request body.
    responses:
      default:
        content:
          application/json:
            schema:
              $ref: "../schemas/environment.yaml#/ConfirmActivationKeyResponse"
        description: Successful operation
    security: []
    tags:
    - Environments
