openapi: 3.0.3
info:
  description: ""
  title: Connection Coordinator API Specification
  version: v1
servers:
- url: /
paths:
  /providers:
    $ref: paths/providers.yaml#/AllProviders
  /providers/{provider}:
    $ref: paths/providers.yaml#/OneProvider
  /providers/{provider}/environments:
    $ref: paths/environments.yaml#/AllEnvironments
  /providers/{provider}/environments/{environment}:
    $ref: paths/environments.yaml#/OneEnvironment
  /providers/{provider}/environments/{environment}/ConfirmActivationKey:
    $ref: paths/environments.yaml#/ConfirmActivationKey
  /providers/{provider}/environments/{environment}/interconnects:
    $ref: paths/interconnects.yaml#/AllInterconnects
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}:
    $ref: paths/interconnects.yaml#/OneInterconnect
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels:
    $ref: paths/channels.yaml#/AllChannels
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels/{channel}:
    $ref: paths/channels.yaml#/OneChannel
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels/{channel}/NotifyMaintenance:
    $ref: paths/channels.yaml#/NotifyMaintenance
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels/{channel}/maintenanceEvents:
    $ref: paths/channels.yaml#/GetMaintenanceEvents
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels/{channel}/macSecKeys:
    $ref: paths/macseckeys.yaml#/AllMacSecKeys  
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/channels/{channel}/macSecKeys/{macSecKey}:
    $ref: paths/macseckeys.yaml#/OneMacSecKey
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections:
    $ref: paths/connections.yaml#/AllConnections
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections/{connection}:
    $ref: paths/connections.yaml#/OneConnection
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections/{connection}/GenerateFeatureGuidance:
    $ref: paths/connections.yaml#/GenerateFeatureGuidance
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections/{connection}/NotifyConnectionStatus:
    $ref: paths/connections.yaml#/NotifyConnectionStatus
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections/{connection}/features:
    $ref: paths/features.yaml#/AllFeatures
  /providers/{provider}/environments/{environment}/interconnects/{interconnect}/connections/{connection}/features/{feature}:
    $ref: paths/features.yaml#/OneFeature
  /providers/{provider}/issues:
    $ref: paths/issues.yaml#/AllIssues
  /providers/{provider}/issues/{issue}:
    $ref: paths/issues.yaml#/OneIssue
  /providers/{provider}/issues/{issue}/Close:
    $ref: paths/issues.yaml#/CloseIssue
  /providers/{provider}/issues/{issue}/comments:
    $ref: paths/issues.yaml#/ListComments
  /providers/{provider}/issues/{issue}/AddComment:
    $ref: paths/issues.yaml#/AddComment
components:
  schemas:
    Provider:
      $ref: schemas/provider.yaml#/Provider
    Environment:
      $ref: schemas/environment.yaml#/Environment
    Interconnect:
      $ref: schemas/interconnect.yaml#/Interconnect
    Channel:
      $ref: schemas/channel.yaml#/Channel
    Connection:
      $ref: schemas/connection.yaml#/Connection
    Feature:
      $ref: schemas/feature.yaml#/Feature
    MacSecKey:
      $ref: schemas/macseckey.yaml#/MacSecKey
    Issue:
      $ref: schemas/issues.yaml#/Issue
  parameters:
    provider:
      $ref: parameters/_index.yaml#/parameters/provider
    environment:
      $ref: parameters/_index.yaml#/parameters/environment
    interconnect:
      $ref: parameters/_index.yaml#/parameters/interconnect
    channel:
      $ref: parameters/_index.yaml#/parameters/channel
    connection:
      $ref: parameters/_index.yaml#/parameters/connection
    feature:
      $ref: parameters/_index.yaml#/parameters/feature
    macSecKey:
      $ref: parameters/_index.yaml#/parameters/macSecKey
    issue:
      $ref: parameters/_index.yaml#/parameters/issue
    alt:
      $ref: parameters/_index.yaml#/parameters/alt
    callback:
      $ref: parameters/_index.yaml#/parameters/callback
    prettyPrint:
      $ref: parameters/_index.yaml#/parameters/prettyPrint
    _.xgafv:
      $ref: parameters/_index.yaml#/parameters/_.xgafv

